version: '3.8'

services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/backend:/app
      - /app/node_modules

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: spacehub
      POSTGRES_PASSWORD: spacehub_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: ./src/frontend/web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./src/frontend/web:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules:
